Repository clts-uniandes/DesarrolloMovil, pull requests merged in 2022-11, with the labels that each got.

#72 Add layouts and viewModel for album list
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/Album.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/AlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/AlbumViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: task

#73 Add data classes and repository for album list
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/AlbumMapper.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/AlbumResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/AlbumRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/AlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/AlbumViewModel.kt
Labels: task

#76 feat: diseño de capa view, pendiente validar uso de Material Design
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
  app/src/main/res/layout/new_album_item.xml
  app/src/main/res/values/strings.xml
Labels: task, user story

#78 Add unit test
  app/build.gradle
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumClient.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/RetrofitBuilder.kt
  app/src/test/java/com/grupo19/ingsoftmoviles/model/data/AlbumMapperTest.kt
  app/src/test/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapterImplTest.kt
  app/src/test/java/com/grupo19/ingsoftmoviles/model/network/readme.md
  app/src/test/java/com/grupo19/ingsoftmoviles/model/readme.md
  app/src/test/java/com/grupo19/ingsoftmoviles/util/FileUtils.kt
  app/src/test/mockito-extensions/org.mockito.plugins.MockMaker
  app/src/test/resources/json/album_response.json
Labels: task

#80 feat: creación componentes tipo Model y ViewModel
  app/src/main/java/com/grupo19/ingsoftmoviles/model/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/AlbumCreate.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceRetrofit.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/AlbumRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/README.md
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/AlbumViewModel.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/NewAlbumViewModel.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/README.md
Labels: task, user story

#81 Add instrumentation test
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/AlbumInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/AlbumDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/CountingIdlingResourceSingleton.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/AlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/AlbumViewModel.kt
  app/src/main/res/layout/activity_album_detail.xml
Labels: task

#82 feat: conexión entre View y ViewModel + interceptor errores de Retrofit
  app/build.gradle
  app/src/main/java/com/grupo19/ingsoftmoviles/model/ResultWrapper.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/AlbumResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/RetrofitBuilder.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/AlbumRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/NewAlbumViewModel.kt
  app/src/main/res/layout/new_album_item.xml
Labels: task, user story

#84 Add method for integration with album detail
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/Album.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/AlbumResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/AlbumRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/AlbumDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/AlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/AlbumViewModel.kt
Labels: task

#85 Feat hu02 detalle album
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity2.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/theme/Color.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/theme/Shape.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/theme/Theme.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/theme/Type.kt
  build.gradle
Labels: task, user story

#86 feat: migracion a material design
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
  app/src/main/res/layout/activity_new_album.xml
  app/src/main/res/layout/material_list_item.xml
  app/src/main/res/layout/new_album_item.xml
Labels: task, user story

#87 Creacion de pupup y conexion con inputs
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/AsociateTrackAlbumActivity.kt
  app/src/main/res/values/strings.xml
Labels: task, user story

#88 Creacion de pupup de creacion de album
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
  app/src/main/res/values/strings.xml
Labels: task, user story

#89 Creacion de readme
  .gitignore
  .idea/deploymentTargetDropDown.xml
  README.md
  resources/readme/capture1.png
  resources/readme/capture2.png
  resources/readme/capture3.png
  resources/readme/capture4.png
  resources/readme/capture5.png
  resources/readme/capture6.png
  resources/readme/capture7.png
Labels: documentation

#90 feat: integrar detalle album
  .idea/androidTestResultsUserPreferences.xml
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity2.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/VinilosApp.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/screen/AlbumDetail.kt
  app/src/main/res/drawable/albumtest.png
Labels: task, user story

#91 clean layouts
  .idea/deploymentTargetDropDown.xml
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/AlbumInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/AlbumRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/AlbumDetailActivity.kt
  app/src/main/res/layout/activity_album_detail.xml
Labels: task

#97 Creacion del layout para listado de artistas
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistsListActivity.kt
  app/src/main/res/layout/activity_artists_list.xml
  app/src/main/res/layout/artist_item.xml
Labels: task, user story

#98 Creacion de model, activity, adapter, service, viewmodel
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/Artist.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistMapper.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceRetrofit.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/ArtistRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistsListActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/ArtistViewModel.kt
  app/src/main/res/layout/activity_artists_list.xml
  app/src/main/res/layout/artist_item.xml
Labels: task, user story

#99 Se habilita la cache de imagenes con Glide en el activity de lista de…
  app/build.gradle
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistAdapter.kt
  app/src/main/res/drawable-v24/ic_broken_image.xml
  app/src/main/res/drawable-v24/loading_animation.xml
  app/src/main/res/drawable-v24/loading_img.xml
Labels: task

#102 Add artist detail layout
  app/src/main/res/layout/artist_detail.xml
Labels: task

#104 Feat integracion navegacion
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistListFragment.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_artist_list.xml
Labels: task

#105 feat: agregar navegacion por drawer
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: task

#106 Add layout for all albums that belongs to artist
  app/src/main/res/layout/activity_artist_detail_album_list.xml
  app/src/main/res/layout/artist_detail_album_item.xml
Labels: task

#108 feat: agregar navegacion a crearcion de album
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/HomeActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumCreateFragment.kt
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: task

#109 Feat date picker material
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
Labels: task

#110 Add artist detail implementation
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistDetailAlbumListActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistsListActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/AlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/ArtistViewModel.kt
  app/src/main/res/layout/activity_artist_detail.xml
  app/src/main/res/layout/activity_artist_detail_album_list.xml
  app/src/main/res/layout/activity_artists_list.xml
  app/src/main/res/values/styles.xml
Labels: task

#111 Add artist detail album list implementation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistDetailAlbumListWrapper.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/ArtistDetailAlbumListActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistDetailAlbumAdapter.kt
  app/src/main/res/layout/activity_artist_detail.xml
  app/src/main/res/layout/activity_artist_detail_album_list.xml
  app/src/main/res/layout/artist_detail_album_item.xml
Labels: task

#112 Fix artist detail - album button name
  app/src/main/res/layout/activity_artist_detail.xml
  app/src/main/res/values/strings.xml
Labels: task

#116 Feat issue93 espresso tests
  .gitignore
  .idea/androidTestResultsUserPreferences.xml
  .idea/encodings.xml
  app/build.gradle
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU01AlbumListInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU02AlbumDetailInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU03ArtistListInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU04ArtistDetailInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU07NewAlbumInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU08NewAlbumWithTrackInsTest.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/NewAlbumActivity.kt
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/values/strings.xml
Labels: task

#120 Add improvments for performance
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/AlbumInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumCreateFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AsociateTrackAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/NewAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/VinilosApp.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistDetailAlbumListActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistListFragment.kt
  app/src/main/res/drawable/albumtest.png
  app/src/main/res/layout/activity_artist_detail.xml
  app/src/main/res/layout/activity_artist_detail_album_list.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_album_create.xml
  app/src/main/res/layout/fragment_collectionist.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: task

#117 Develop
  .gitignore
  .idea/androidTestResultsUserPreferences.xml
  .idea/encodings.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/AlbumInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU01AlbumListInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU02AlbumDetailInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU03ArtistListInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU04ArtistDetailInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU07NewAlbumInstrumentedTest.kt
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU08NewAlbumWithTrackInsTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/Artist.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistDetailAlbumListWrapper.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistMapper.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/ArtistResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceRetrofit.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/ArtistRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/HomeActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/MainActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/AlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistDetailAlbumAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AsociateTrackAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/NewAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/VinilosApp.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistDetailAlbumListActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/collectionist/CollectionistFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/ArtistViewModel.kt
  app/src/main/res/drawable-v24/ic_broken_image.xml
  app/src/main/res/drawable-v24/loading_animation.xml
  app/src/main/res/drawable-v24/loading_img.xml
  app/src/main/res/drawable/albumtest.png
  app/src/main/res/drawable/ic_baseline_album_24.xml
  app/src/main/res/drawable/ic_baseline_people_24.xml
  app/src/main/res/drawable/ic_baseline_stars_24.xml
  app/src/main/res/layout/activity_artist_detail.xml
  app/src/main/res/layout/activity_artist_detail_album_list.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/artist_detail_album_item.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/fragment_album_list.xml
  app/src/main/res/layout/fragment_artist_list.xml
  app/src/main/res/layout/fragment_collectionist.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: task, user story

#131 feat: layout+ui para fragmento de lista de coleccionistas
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/collectionist/CollectionistListFragment.kt
  app/src/main/res/layout/collectionist_list_item.xml
  app/src/main/res/layout/fragment_collectionist.xml
  app/src/main/res/layout/fragment_collectionist_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: task, user story

#132 feat: closes #36
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/CollectorResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/Comment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/collector/CollectorServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/collector/CollectorServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/collector/CollectorServiceRetrofit.kt
Labels: task, user story

#133 feat: se completan componentes para ViewModel asociado
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/CollectorRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/CollectorListViewModel.kt
Labels: task, user story

#134 feat: se conectan componentes UI a ViewModel correspondiente
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/CollectorListAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/collectionist/CollectionistListFragment.kt
  app/src/main/res/layout/collectionist_list_item.xml
  app/src/main/res/layout/fragment_collectionist_list.xml
Labels: task, user story

#136 feat: se renombran componentes para correctitud en ingles y brevedad,…
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/HomeActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/CollectorListAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/collector/CollectorListFragment.kt
  app/src/main/res/layout/activity_new_album.xml
  app/src/main/res/layout/collector_list_item.xml
  app/src/main/res/layout/fragment_collector_list.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: task, user story

#137 Add navigation between album detail and create tack
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AsociateTrackAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/screen/AlbumDetail.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/theme/Color.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/theme/Theme.kt
  app/src/main/res/layout/activity_asociate_track_album.xml
Labels: task

#138 Add return navigation after associate a track
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AsociateTrackAlbumActivity.kt
Labels: task

#139 Add album detail from service adapter
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/model/data/AlbumResponse.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/RetrofitBuilder.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/album/AlbumServiceRetrofit.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/AlbumRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AlbumListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/AsociateTrackAlbumActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/VinilosApp.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/screen/AlbumDetail.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/AlbumDetailViewModel.kt
Labels: task

#140 Feat hu08 asociar track navegacion
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/NewAlbumActivity.kt
Labels: enhancement

#145 Add artist detail service adapter
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/artist/ArtistServiceRetrofit.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/ArtistRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/artist/ArtistListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/ArtistDetailViewModel.kt
  app/src/main/res/layout/activity_artist_detail.xml
Labels: task, user story

#144 fix: Se soluciona el error que se tiene al ejecutar las pruebas cambi…
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/AlbumInstrumentedTest.kt
Labels: bug

#143 Validaciones de formulario crear album y funcionalidad
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/NewAlbumActivity.kt
  app/src/main/res/layout/activity_new_album.xml
Labels: bug, enhancement

#146 feat: se habilita cache de Retrofit modo online
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/RetrofitBuilder.kt
Labels: enhancement, task

#147 feat: agregar detalle de colleccionista
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/drawable/ic_launcher_background.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/collector/CollectorServiceAdapter.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/collector/CollectorServiceAdapterImpl.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/network/collector/CollectorServiceRetrofit.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/model/repo/CollectorRepository.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/Constants.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/collector/CollectorDetailActivity.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/collector/CollectorListFragment.kt
  app/src/main/java/com/grupo19/ingsoftmoviles/viewmodel/CollectorDetailViewModel.kt
  app/src/main/res/drawable/ic_baseline_email_24.xml
  app/src/main/res/drawable/ic_baseline_local_phone_24.xml
  app/src/main/res/layout/activity_collector_detail.xml
Labels: task, user story
