Repository clts-uniandes/DesarrolloMovil, pull requests merged in 2022-12, with the labels that each got.

#149 Retrocompatibilidad Cache Glide
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistAdapter.kt
Labels: bug

#150 fix: se habilita un scroll view para casos en que pantallas pequeñas …
  app/src/main/res/layout/activity_new_album.xml
Labels: enhancement

#151 fix: se compensa error de dia desfasado por libreria para soportar AP…
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/album/NewAlbumActivity.kt
Labels: bug, task

#152 fix: se arregla bug 115, closes #115
  app/src/main/java/com/grupo19/ingsoftmoviles/ui/adapters/ArtistAdapter.kt
Labels: bug

#153 fix: quitar icono de profile como icono de app
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/drawable/profile.png
  app/src/main/res/layout/activity_collector_detail.xml
Labels: bug

#158 Adicion de dependencias para la ejecucion de test en api 33
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle
Labels: bug

#157 Adicion de pruba para la historia de usuario 06
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU06CollectorDetailInstrumentedTest.kt
Labels: task, user story

#156 Adicion de pruba para la historia de usuario 05
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU05CollectorListInstrumentedTest.kt
Labels: task, user story

#160 Ajuste en nombre de clases de los test para hu06 y hu05
  app/src/androidTest/java/com/grupo19/ingsoftmoviles/HU06CollectorDetailInstrumentedTest.kt
Labels: bug
